import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/Button'
import Heading from '../components/Heading'
import Polaroid from '../components/Polaroid'
import TextBox from '../components/TextBox'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Covered+By+Your+Grace&family=Sora:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
        <link
          rel="preload"
          href="/fonts/Lazer84.ttf"
          as="font"
          crossOrigin=""
        />
      </Head>

      <main>
        <Heading />
        <div className="flex">
          <Polaroid />
          <TextBox text="Let's celebrate being old together" />
          <Button text="RSVP" />
        </div>
      </main>
    </div>
  )
}
